# Generated by Django 4.1.3 on 2022-12-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('task_name', models.CharField(max_length=128)),
                ('task_desc', models.CharField(max_length=512)),
                ('status', models.BooleanField()),
                ('repeat', models.BooleanField()),
                ('deadline', models.DateField(blank=True, null=True)),
                ('repeattype', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128)),
                ('mail_address', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('latest_update', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
